name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build-prod
              env:
                  PUBLIC_URL: https://maloo.ski/

            - name: Prevent Jekyll
              run: touch dist/.nojekyll

            - name: Copy CNAME
              run: cp CNAME dist/CNAME

            - name: Deploy to Github Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2.0.0
              with:
                  target_branch: gh-pages
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
